In [1]:
import time
from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import pandas as pd
import itertools

wd='PATH_TO_ENTTEMPLATES_DATA_ROOT/Analysis/python_Similarity/data/'
output='PATH_TO_ENTTEMPLATES_DATA_ROOT/Analysis/python_Similarity/output/'

# Load pre-trained SentenceTransformer
sbert_model = SentenceTransformer('all-distilroberta-v1')

# Load data
df = pd.read_pickle(wd+'company_embedding_ST')
df = df.sort_values(by=['fullname'])
df=df[df['fullname']== 'AI ML|Vertical Applications|Consumer']

In [2]:
df

,companyid,fullname,embedding
254864,56133-10,AI ML|Vertical Applications|Consumer,"[-7.123363e-05, -0.033342585, 0.05527848, -0.0..."
328339,439013-71,AI ML|Vertical Applications|Consumer,"[-0.016678385, -0.034818947, -0.008875517, 0.0..."
39636,399714-85,AI ML|Vertical Applications|Consumer,"[-0.0065959916, -0.050884463, -0.006652736, -0..."
254653,53503-48,AI ML|Vertical Applications|Consumer,"[-0.04566997, -0.043910053, 0.0076927086, -0.0..."
206602,160346-89,AI ML|Vertical Applications|Consumer,"[-0.025326159, -0.036783617, 0.014422003, -0.0..."
...,...,...,...
327977,110776-69,AI ML|Vertical Applications|Consumer,"[-0.025744675, -0.06513593, -0.009325135, -0.0..."
37862,315972-73,AI ML|Vertical Applications|Consumer,"[-0.002767625, -0.027123047, 0.02105413, 0.005..."
210634,462453-13,AI ML|Vertical Applications|Consumer,"[-0.034871046, -0.021072688, -1.1106268e-05, -..."
155898,83752-75,AI ML|Vertical Applications|Consumer,"[-0.03193334, 0.002922773, 0.04413781, -0.0466..."
183635,58253-95,AI ML|Vertical Applications|Consumer,"[-0.008885957, -0.0047575976, 0.06398351, -0.0..."

In [11]:
names_to_exclude = [
    'AI ML|AI & ML Semiconductors|Edge AI Software',
    'AI ML|AI & ML Semiconductors|Intelligent Sensors & Devices',
    'AI ML|AI & ML Semiconductors|Processor Design',
    'AI ML|Autonomous Machines|Autonomous Vehicles',
    'AI ML|Autonomous Machines|Intelligent Robotics',
    'AI ML|Horizontal Platforms|AI Automation Platforms',
    'AI ML|Horizontal Platforms|AI Core',
    'AI ML|Horizontal Platforms|Computer Vision',
    'AI ML|Horizontal Platforms|Natural Language Technology',
    'AI ML|Vertical Applications|Consumer',
    'AI ML|Vertical Applications|Financial Services',
    'AI ML|Vertical Applications|Healthcare',
    "AI ML|Vertical Applications|Industrial",
    "AI ML|Vertical Applications|Information Technology",
    "AI ML|Vertical Applications|Mobility",
    "AgTech|Ag biotech|Animal biotech",
    "AgTech|Ag biotech|Biomaterials",
    "AgTech|Ag biotech|Plant biotech",
    "AgTech|Ag biotech|Plant data & analysis",
    "AgTech|Agrifinance & eCommerce|Agribusiness marketplaces",
    "AgTech|Agrifinance & eCommerce|Finance & insurance",
    "AgTech|Animal ag|Aquaculture",
    "AgTech|Animal ag|Insect farming",
    "AgTech|Animal ag|Livestock & land animal tech",
    "AgTech|Animal ag|Pollination tech",
    "AgTech|Indoor farming|Components",
    "AgTech|Indoor farming|Growers",
    "AgTech|Indoor farming|Systems",
    "AgTech|Precision ag|Drones & imagery analytics",
    "AgTech|Precision ag|Farm management software",
    "AgTech|Precision ag|Field IoT",
    "AgTech|Precision ag|Robotics & smart field equipment",
    "Blockchain|Blockchain|Blockchain",
    "Blockchain|Enterprise|Enterprise",
    "Blockchain|Financial Services|Financial Services",
    "Blockchain|Infrastructure|Infrastructure",
    "Blockchain|NFTs|NFTs",
    "Carbon and Emissions Tech|Built Environment|Building Energy Efficiency",
    "Carbon and Emissions Tech|Built Environment|Green Construction",
    "Carbon and Emissions Tech|Built Environment|Heating and Cooling",
    "Carbon and Emissions Tech|Carbon Tech|Biological Carbon Removal",
    "Carbon and Emissions Tech|Carbon Tech|Carbon Accounting/Analytics",
]


df = df[~df['fullname'].isin(names_to_exclude)]
df

,companyid,fullname,embedding
13679,54707-41,Carbon and Emissions Tech|Carbon Tech|Carbon F...,"[-0.021155236, -0.002549114, -0.0106962565, -0..."
271785,115456-06,Carbon and Emissions Tech|Carbon Tech|Carbon F...,"[0.0025053257, 0.013508373, -0.0143952, -0.030..."
224232,53713-81,Carbon and Emissions Tech|Carbon Tech|Carbon F...,"[-0.00012465817, 0.0038097452, 0.016205737, -0..."
238794,53755-30,Carbon and Emissions Tech|Carbon Tech|Carbon F...,"[0.01175531, 0.034781028, -0.023994312, -0.052..."
119779,484154-74,Carbon and Emissions Tech|Carbon Tech|Carbon F...,"[-0.017856784, -0.002753013, -0.009651142, -0...."
...,...,...,...
284241,110508-31,Supply Chain Tech|Warehousing tech|Warehouse a...,"[-0.020348571, -0.007767355, -0.023641346, 0.0..."
39323,232395-04,Supply Chain Tech|Warehousing tech|Warehouse a...,"[-0.011821735, -0.028306404, -0.0102774585, 0...."
88496,148163-68,Supply Chain Tech|Warehousing tech|Warehouse a...,"[-0.029778404, -0.020195313, 0.020117922, 0.01..."
59489,251407-00,Supply Chain Tech|Warehousing tech|Warehouse a...,"[-0.048782956, -0.042804226, 0.01670886, 0.026..."
138858,65614-15,Supply Chain Tech|Warehousing tech|Warehouse a...,"[-0.01718627, -0.013831111, -0.0014301647, -0...."

In [3]:
# Initialize list to store results
results = []

# Initialize counter and timer
counter = 0
start_time = time.time()

# Group by 'fullname' and iterate over each group
for name, group in df.groupby('fullname'):
    # Get all company pairs within this group
    print('working on '+name)
    for (idx1, row1), (idx2, row2) in itertools.combinations(group.iterrows(), 2):
        # Start timer for this calculation
        calc_start_time = time.time()
        # Calculate similarity between the two companies' descriptions
        similarity = cosine_similarity([row1['embedding']], [row2['embedding']])[0][0]
        
        # Store the result
        results.append({
            'companyid1': row1['companyid'],
            'fullname1': row1['fullname'],
            'companyid2': row2['companyid'],
            'fullname2': row2['fullname'],
            'similarity': similarity
        })
        
        # Increment counter and check if it's a multiple of 1000
        counter += 1
        if counter % 1000000 == 0:
            # Calculate time consumed
            total_time = time.time() - start_time
            print(f'{counter/1000000} million finished; time consumed in total: {total_time:.2f} seconds.')
    similarity_df_ST = pd.DataFrame(results)
    name = name.replace("/", "_")
    similarity_df_ST.to_csv(output+'similarity_ST_'+ name + '.csv')
    print(name+' finished')
    results = []

working on AI ML|Vertical Applications|Consumer
1.0 million finished; time consumed in total: 74.58 seconds.
2.0 million finished; time consumed in total: 148.27 seconds.
3.0 million finished; time consumed in total: 221.27 seconds.
4.0 million finished; time consumed in total: 293.68 seconds.
5.0 million finished; time consumed in total: 366.44 seconds.
6.0 million finished; time consumed in total: 439.39 seconds.
7.0 million finished; time consumed in total: 511.94 seconds.
8.0 million finished; time consumed in total: 584.99 seconds.
9.0 million finished; time consumed in total: 658.46 seconds.
10.0 million finished; time consumed in total: 732.04 seconds.
11.0 million finished; time consumed in total: 805.79 seconds.
12.0 million finished; time consumed in total: 878.43 seconds.
13.0 million finished; time consumed in total: 952.82 seconds.
14.0 million finished; time consumed in total: 1024.50 seconds.
15.0 million finished; time consumed in total: 1097.83 seconds.
16.0 million finished; time consumed in total: 1168.84 seconds.
17.0 million finished; time consumed in total: 1240.10 seconds.
18.0 million finished; time consumed in total: 1311.43 seconds.
19.0 million finished; time consumed in total: 1382.53 seconds.
20.0 million finished; time consumed in total: 1453.84 seconds.
21.0 million finished; time consumed in total: 1525.21 seconds.
22.0 million finished; time consumed in total: 1596.67 seconds.
23.0 million finished; time consumed in total: 1668.05 seconds.
24.0 million finished; time consumed in total: 1739.27 seconds.
25.0 million finished; time consumed in total: 1810.65 seconds.
26.0 million finished; time consumed in total: 1882.20 seconds.
27.0 million finished; time consumed in total: 1953.65 seconds.
28.0 million finished; time consumed in total: 2025.18 seconds.
29.0 million finished; time consumed in total: 2096.64 seconds.
30.0 million finished; time consumed in total: 2168.01 seconds.
31.0 million finished; time consumed in total: 2239.59 seconds.
32.0 million finished; time consumed in total: 2312.75 seconds.
33.0 million finished; time consumed in total: 2386.58 seconds.
34.0 million finished; time consumed in total: 2458.63 seconds.
35.0 million finished; time consumed in total: 2530.01 seconds.
36.0 million finished; time consumed in total: 2601.47 seconds.
37.0 million finished; time consumed in total: 2672.61 seconds.
38.0 million finished; time consumed in total: 2743.92 seconds.
39.0 million finished; time consumed in total: 2815.71 seconds.
40.0 million finished; time consumed in total: 2886.92 seconds.
41.0 million finished; time consumed in total: 2958.02 seconds.
42.0 million finished; time consumed in total: 3029.49 seconds.
43.0 million finished; time consumed in total: 3100.54 seconds.
44.0 million finished; time consumed in total: 3171.62 seconds.
45.0 million finished; time consumed in total: 3243.00 seconds.
46.0 million finished; time consumed in total: 3314.14 seconds.
47.0 million finished; time consumed in total: 3384.74 seconds.
48.0 million finished; time consumed in total: 3455.55 seconds.
49.0 million finished; time consumed in total: 3526.26 seconds.
50.0 million finished; time consumed in total: 3597.19 seconds.
51.0 million finished; time consumed in total: 3668.00 seconds.
52.0 million finished; time consumed in total: 3738.58 seconds.
53.0 million finished; time consumed in total: 3809.24 seconds.
54.0 million finished; time consumed in total: 3880.09 seconds.
55.0 million finished; time consumed in total: 3950.99 seconds.
56.0 million finished; time consumed in total: 4021.73 seconds.
57.0 million finished; time consumed in total: 4092.79 seconds.
58.0 million finished; time consumed in total: 4163.95 seconds.
59.0 million finished; time consumed in total: 4235.40 seconds.
60.0 million finished; time consumed in total: 4306.69 seconds.
61.0 million finished; time consumed in total: 4377.90 seconds.
62.0 million finished; time consumed in total: 4449.17 seconds.
63.0 million finished; time consumed in total: 4520.44 seconds.
64.0 million finished; time consumed in total: 4592.68 seconds.
65.0 million finished; time consumed in total: 4664.02 seconds.
66.0 million finished; time consumed in total: 4735.45 seconds.
67.0 million finished; time consumed in total: 4806.69 seconds.
68.0 million finished; time consumed in total: 4877.76 seconds.
69.0 million finished; time consumed in total: 4949.39 seconds.
70.0 million finished; time consumed in total: 5020.55 seconds.
71.0 million finished; time consumed in total: 5091.64 seconds.
72.0 million finished; time consumed in total: 5162.77 seconds.
73.0 million finished; time consumed in total: 5234.11 seconds.
74.0 million finished; time consumed in total: 5305.63 seconds.
75.0 million finished; time consumed in total: 5377.09 seconds.
76.0 million finished; time consumed in total: 5448.47 seconds.
77.0 million finished; time consumed in total: 5520.46 seconds.
78.0 million finished; time consumed in total: 5591.86 seconds.
79.0 million finished; time consumed in total: 5663.43 seconds.
80.0 million finished; time consumed in total: 5735.08 seconds.
81.0 million finished; time consumed in total: 5806.85 seconds.
82.0 million finished; time consumed in total: 5878.99 seconds.
83.0 million finished; time consumed in total: 5950.50 seconds.
84.0 million finished; time consumed in total: 6021.84 seconds.
85.0 million finished; time consumed in total: 6093.43 seconds.
86.0 million finished; time consumed in total: 6164.70 seconds.
87.0 million finished; time consumed in total: 6236.35 seconds.
88.0 million finished; time consumed in total: 6307.62 seconds.
89.0 million finished; time consumed in total: 6379.26 seconds.
90.0 million finished; time consumed in total: 6451.16 seconds.
91.0 million finished; time consumed in total: 6522.47 seconds.
92.0 million finished; time consumed in total: 6593.93 seconds.
93.0 million finished; time consumed in total: 6679.05 seconds.
94.0 million finished; time consumed in total: 6750.84 seconds.
95.0 million finished; time consumed in total: 6822.00 seconds.
96.0 million finished; time consumed in total: 6893.23 seconds.
97.0 million finished; time consumed in total: 6964.49 seconds.
98.0 million finished; time consumed in total: 7035.70 seconds.
99.0 million finished; time consumed in total: 7107.22 seconds.
100.0 million finished; time consumed in total: 7178.63 seconds.
101.0 million finished; time consumed in total: 7250.06 seconds.
102.0 million finished; time consumed in total: 7321.54 seconds.
103.0 million finished; time consumed in total: 7393.10 seconds.
104.0 million finished; time consumed in total: 7465.04 seconds.
105.0 million finished; time consumed in total: 7537.21 seconds.
106.0 million finished; time consumed in total: 7608.77 seconds.
107.0 million finished; time consumed in total: 7680.11 seconds.
108.0 million finished; time consumed in total: 7751.37 seconds.
109.0 million finished; time consumed in total: 7822.85 seconds.
110.0 million finished; time consumed in total: 7894.04 seconds.
111.0 million finished; time consumed in total: 7965.29 seconds.
112.0 million finished; time consumed in total: 8036.48 seconds.
113.0 million finished; time consumed in total: 8107.65 seconds.
114.0 million finished; time consumed in total: 8179.06 seconds.
115.0 million finished; time consumed in total: 8250.41 seconds.
116.0 million finished; time consumed in total: 8321.81 seconds.
117.0 million finished; time consumed in total: 8393.00 seconds.
118.0 million finished; time consumed in total: 8464.55 seconds.
119.0 million finished; time consumed in total: 8535.87 seconds.
120.0 million finished; time consumed in total: 8607.31 seconds.
121.0 million finished; time consumed in total: 8680.02 seconds.
122.0 million finished; time consumed in total: 8752.51 seconds.
123.0 million finished; time consumed in total: 8824.27 seconds.
124.0 million finished; time consumed in total: 8895.59 seconds.
125.0 million finished; time consumed in total: 8966.82 seconds.
126.0 million finished; time consumed in total: 9039.00 seconds.
127.0 million finished; time consumed in total: 9110.65 seconds.
128.0 million finished; time consumed in total: 9182.38 seconds.
129.0 million finished; time consumed in total: 9253.64 seconds.
130.0 million finished; time consumed in total: 9325.00 seconds.
131.0 million finished; time consumed in total: 9396.61 seconds.
132.0 million finished; time consumed in total: 9468.06 seconds.
133.0 million finished; time consumed in total: 9539.38 seconds.
134.0 million finished; time consumed in total: 9610.95 seconds.
135.0 million finished; time consumed in total: 9682.71 seconds.
136.0 million finished; time consumed in total: 9754.02 seconds.
137.0 million finished; time consumed in total: 9825.51 seconds.
138.0 million finished; time consumed in total: 9896.94 seconds.
139.0 million finished; time consumed in total: 9968.42 seconds.
140.0 million finished; time consumed in total: 10040.29 seconds.
141.0 million finished; time consumed in total: 10112.15 seconds.
142.0 million finished; time consumed in total: 10184.20 seconds.
143.0 million finished; time consumed in total: 10257.15 seconds.
144.0 million finished; time consumed in total: 10329.60 seconds.
145.0 million finished; time consumed in total: 10402.92 seconds.
146.0 million finished; time consumed in total: 10475.03 seconds.
147.0 million finished; time consumed in total: 10546.21 seconds.
148.0 million finished; time consumed in total: 10618.04 seconds.
149.0 million finished; time consumed in total: 10689.61 seconds.
150.0 million finished; time consumed in total: 10761.14 seconds.
151.0 million finished; time consumed in total: 10833.01 seconds.
152.0 million finished; time consumed in total: 10904.50 seconds.
153.0 million finished; time consumed in total: 10975.89 seconds.
154.0 million finished; time consumed in total: 11048.73 seconds.
155.0 million finished; time consumed in total: 11120.48 seconds.
156.0 million finished; time consumed in total: 11192.46 seconds.
157.0 million finished; time consumed in total: 11264.60 seconds.
158.0 million finished; time consumed in total: 11336.09 seconds.
159.0 million finished; time consumed in total: 11408.17 seconds.
160.0 million finished; time consumed in total: 11479.96 seconds.
161.0 million finished; time consumed in total: 11551.77 seconds.
162.0 million finished; time consumed in total: 11623.96 seconds.
163.0 million finished; time consumed in total: 11695.35 seconds.
164.0 million finished; time consumed in total: 11767.46 seconds.
165.0 million finished; time consumed in total: 11839.47 seconds.
166.0 million finished; time consumed in total: 11910.98 seconds.
167.0 million finished; time consumed in total: 11983.54 seconds.
168.0 million finished; time consumed in total: 12055.89 seconds.
169.0 million finished; time consumed in total: 12128.53 seconds.
170.0 million finished; time consumed in total: 12200.58 seconds.
171.0 million finished; time consumed in total: 12272.80 seconds.
172.0 million finished; time consumed in total: 12345.29 seconds.
173.0 million finished; time consumed in total: 12418.40 seconds.
174.0 million finished; time consumed in total: 12491.06 seconds.
175.0 million finished; time consumed in total: 12563.76 seconds.
176.0 million finished; time consumed in total: 12635.08 seconds.
177.0 million finished; time consumed in total: 12707.61 seconds.
178.0 million finished; time consumed in total: 12779.09 seconds.
179.0 million finished; time consumed in total: 12850.66 seconds.
180.0 million finished; time consumed in total: 12922.06 seconds.
181.0 million finished; time consumed in total: 12993.85 seconds.
182.0 million finished; time consumed in total: 13065.71 seconds.
183.0 million finished; time consumed in total: 13137.21 seconds.
184.0 million finished; time consumed in total: 13208.78 seconds.
185.0 million finished; time consumed in total: 13280.79 seconds.
186.0 million finished; time consumed in total: 13352.16 seconds.
187.0 million finished; time consumed in total: 13424.18 seconds.
188.0 million finished; time consumed in total: 13495.52 seconds.
189.0 million finished; time consumed in total: 13566.62 seconds.
190.0 million finished; time consumed in total: 13637.93 seconds.
191.0 million finished; time consumed in total: 13709.30 seconds.
192.0 million finished; time consumed in total: 13781.06 seconds.
193.0 million finished; time consumed in total: 13852.70 seconds.
194.0 million finished; time consumed in total: 13924.83 seconds.
195.0 million finished; time consumed in total: 13997.43 seconds.
196.0 million finished; time consumed in total: 14069.82 seconds.
197.0 million finished; time consumed in total: 14141.91 seconds.
198.0 million finished; time consumed in total: 14213.19 seconds.
199.0 million finished; time consumed in total: 14284.74 seconds.
200.0 million finished; time consumed in total: 14356.07 seconds.
201.0 million finished; time consumed in total: 14427.30 seconds.
202.0 million finished; time consumed in total: 14499.32 seconds.
203.0 million finished; time consumed in total: 14571.17 seconds.
204.0 million finished; time consumed in total: 14642.70 seconds.
205.0 million finished; time consumed in total: 14714.01 seconds.
206.0 million finished; time consumed in total: 14785.22 seconds.
207.0 million finished; time consumed in total: 14857.48 seconds.
208.0 million finished; time consumed in total: 14930.09 seconds.
209.0 million finished; time consumed in total: 15001.56 seconds.
210.0 million finished; time consumed in total: 15073.67 seconds.
211.0 million finished; time consumed in total: 15145.80 seconds.
212.0 million finished; time consumed in total: 15218.16 seconds.
213.0 million finished; time consumed in total: 15289.99 seconds.
214.0 million finished; time consumed in total: 15361.97 seconds.
215.0 million finished; time consumed in total: 15433.50 seconds.
216.0 million finished; time consumed in total: 15504.95 seconds.
217.0 million finished; time consumed in total: 15577.16 seconds.
218.0 million finished; time consumed in total: 15648.46 seconds.
219.0 million finished; time consumed in total: 16067.35 seconds.
220.0 million finished; time consumed in total: 16138.59 seconds.
221.0 million finished; time consumed in total: 16210.41 seconds.
222.0 million finished; time consumed in total: 16282.12 seconds.
223.0 million finished; time consumed in total: 16353.86 seconds.
224.0 million finished; time consumed in total: 16425.65 seconds.
225.0 million finished; time consumed in total: 16497.29 seconds.
226.0 million finished; time consumed in total: 16569.18 seconds.
227.0 million finished; time consumed in total: 16641.02 seconds.

In [6]:
similarity_df_ST

,companyid1,fullname1,companyid2,fullname2,similarity
0,463332-34,Carbon and Emissions Tech|Carbon Tech|Carbon A...,459260-29,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.749403
1,463332-34,Carbon and Emissions Tech|Carbon Tech|Carbon A...,92083-06,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.727068
2,463332-34,Carbon and Emissions Tech|Carbon Tech|Carbon A...,85885-57,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.680855
3,463332-34,Carbon and Emissions Tech|Carbon Tech|Carbon A...,416571-04,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.860592
4,463332-34,Carbon and Emissions Tech|Carbon Tech|Carbon A...,442986-67,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.770729
...,...,...,...,...,...
11170,232655-77,Carbon and Emissions Tech|Carbon Tech|Carbon A...,437142-07,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.530019
11171,232655-77,Carbon and Emissions Tech|Carbon Tech|Carbon A...,279496-27,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.587416
11172,343107-46,Carbon and Emissions Tech|Carbon Tech|Carbon A...,437142-07,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.738416
11173,343107-46,Carbon and Emissions Tech|Carbon Tech|Carbon A...,279496-27,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.500635
11174,437142-07,Carbon and Emissions Tech|Carbon Tech|Carbon A...,279496-27,Carbon and Emissions Tech|Carbon Tech|Carbon A...,0.689659